### ISSUE TITLE
2.5 fails to work on Lollipop 

### ISSUE THREAD

**Issue by gerroon** [PaulWoitaschek/MaterialAudiobookPlayer#380] opened 2015-12-29 20:47 UTC
Hi

I upgraded from 2.4 but my list comes up empty. I wnet ahead, deleted and readded my folders (they are on sdcard1) nothing comes up. Is it possible that the database conversion fails? 2.4x works fine with the same mounts.

thanks

**Comment by amorrn** [comment] 2015-12-29 21:58
I experienced the same issue with the 2.5.0.3 update on LP.

**Comment by amorrn** [comment] 2015-12-29 22:25
When reinstalling 2.4.2.2 (last version before 2.5) I noticed that when selecting the folders I can see the media files inside the folders. On 2.5 I don't see any files in the folder selector even though the files are still there.

**Comment by onespaceman** [comment] 2015-12-29 22:39
Same issue on Marshmallow, version 2.5.0.3.

**Comment by PaulWoitaschek** [comment] 2015-12-29 23:29
Should be fixed as of 2.5.0.4.

**Comment by irregularisnotrandom** [comment] 2015-12-31 16:50
2.5.0.4 did not help. It immediately crashes during opening. I had to roll back..

**Comment by PaulWoitaschek** [comment] 2016-01-04 18:57
I added a test simulating the behavior of adding and removing books but could not find any unexpected behavior.

Can you check [this version](https://www.dropbox.com/s/jpngb9evtxrk1qt/96-snapshot-96-audiobook-debug.apk?dl=0)? It logs to the external storage in a file named `materialaudiobookplayer.log`. If you can reproduce the crash and send the log to me it might bring me on the trail.

**Comment by irregularisnotrandom** [comment] 2016-01-05 15:32
hi

I can test the version but installing and uninstalling is not fun whatsoever because everytime i have to go back to a stable version i loose all my MP database.

**Comment by PaulWoitaschek** [comment] 2016-01-05 15:33
It's a debug version which technically installs as a second app. It will show up as `[DBG] Material Player`

**Closed** 2016-01-14 11:06 UTC
Labels: more information needed
