### ISSUE TITLE
Some files show negative start time and will not play?

### ISSUE THREAD

**Issue by neobithia** [PaulWoitaschek/MaterialAudiobookPlayer#588] opened 2017-05-19 19:07 UTC
![screenshot_20170519-130530 1](https://cloud.githubusercontent.com/assets/5649096/26263003/19f85156-3c94-11e7-893f-f03257d290d3.png)

Some files show negative start time and will not play?  The files are not corrupt, they play fine on my Alienware Windows 10 laptop.  All of the chapters from the same folder show the same negative start time and will not play.

**Comment by PaulWoitaschek** [comment] 2017-05-21 20:34
Can you send me such a file? Just because one media player plays it it does not mean that the file is not corrupt.

**Comment by gwarser** [comment] 2017-05-26 10:43
Happens to me too (shows -1). I fixed it by cleaning app data in android applications settings.

**Comment by PaulWoitaschek** [comment] 2017-05-26 10:44
Can you send me such a file?

**Comment by gwarser** [comment] 2017-05-26 10:48
Will try to find it first (this was in previous book).

**Comment by gwarser** [comment] 2017-05-26 13:43
Looks like my issue is not about files. I hit this when using Endomodo feature to automatically pause music when communicates about route/training are played. When this autopause happens on the beginning of the audiobook track, and you have set automatic rewind with bit higher value, then timer is "rewind" to negative value. You can reproduce by fast pausing/resuming on the beginning of the track using applet in android notification area.

**Comment by PaulWoitaschek** [comment] 2017-05-26 14:00
Thanks, I could reproduce that.

Can't you click the seek bar to go back to the positive area?

**Comment by gwarser** [comment] 2017-05-26 14:32
Yes, forward button also seems to work. Only play/pause is broken.

**Comment by PaulWoitaschek** [comment] 2017-05-26 14:34
But after you are in the postiive area, play pause works again right?

**Comment by gwarser** [comment] 2017-05-26 15:16
Yes.

**Comment by PaulWoitaschek** [comment] 2017-05-27 21:11
Thanks. Should be fixed as of f0e37ea694ae3458eea0ce0a58bebfc8d75dd2a5

**Closed by PaulWoitaschek** 2017-05-27 21:11 UTC
