### ISSUE TITLE
Book adding is slow

### ISSUE THREAD

**Issue by nioncode** [PaulWoitaschek/MaterialAudiobookPlayer#586] opened 2017-05-08 11:07 UTC
Since changing the duration lookup to be based on ExoPlayer, it takes really long to add my books on a fresh install.
Currently, I have 4 books on my device with all of them having ~100 chapters / files and the scan takes 53 seconds. It takes quite long for the first book to even appear in the list.

On 3.3-RC2, it takes only 7 seconds.

**Comment by PaulWoitaschek** [comment] 2017-05-08 11:21
I know; this is an inconvenient side effect. I created an issue here:

https://github.com/google/ExoPlayer/issues/2762

The problem is that with new supported file types, we can't really use the MetaDataRetrieiver any longer for parsing the durations because now handling these is kind of exoplayer specific.

What we could do however is to first make an attempt to parse the duration from the `MetaDataRetrieiver` and only if that fails use ExoPlayer for parsing. Would like like to make a PR for that?

**Comment by nioncode** [comment] 2017-05-08 11:24
Which of the new supported file types would that be? We could also look into using https://github.com/wseemann/FFmpegMediaMetadataRetriever/, maybe that one supports all needed formats and is reasonably quick?

Otherwise, using MediaMetadataRetriever and on error use ExoPlayer sounds like a good idea. Will do a PR for this soon.

**Comment by PaulWoitaschek** [comment] 2017-05-08 11:44
I don't think these two can easily be merged. Also the code smells a little for me with all its uncommented sections.

I would not differentiate the file formats as Android might support them in the future and after checking a file with ExoPlayer we check it with the MMR anyways. So we should just invert that and check with MMR first and just skip the ExoPlayer check if we have a result.

**Comment by PaulWoitaschek** [comment] 2017-05-14 11:30
I investigated further on this. For me it does make very little difference. Are you sure these 7 seconds are a fresh scan? Because once scanned these values are taken from the db and the files are only scanned when are modified in size.

For me it's ExoPlayer: 24ms, MMR: 140ms.

**Comment by nioncode** [comment] 2017-05-15 09:33
Yes, this was a fresh scan. Once scanned, everything appears instantly (because like you said it's just taken from the database).

> For me it's ExoPlayer: 24s, MMR: 140s.

So ExoPlayer is faster in your case?

**Closed** 2017-05-21 20:45 UTC
