### ISSUE TITLE
Issue: Player crashes after sleep timer runs up

### ISSUE THREAD

**Issue by allmynamesweretakenomoreideas** [PaulWoitaschek/MaterialAudiobookPlayer#430] opened 2016-03-11 21:26 UTC
The player process just got killed when the sleep timer finishes. I expect the player to be persistent in stop mode. Device: Motorola XT1068 Android 5.0.2. Stock.

**Comment by kevmitch** [comment] 2016-03-11 21:43
I had noticed that when the sleep timer finishes, there is no longer any Material Player "tile" (or whatever it's called) on the lock screen so you can't just hit play again. Not sure if it is a actually a "crash" or by design.

I don't really mind too much since I typically also have to re-enable the sleep timer, which requires unlocking the phone anyway.

**Comment by PaulWoitaschek** [comment] 2016-03-11 21:53
I don't see the player crashing. Are you sure you mean it crashes? If so please post a comment here and I'll reopen this immediately.

If it is just stopping: Yes, that's intended. When sending the player to sleep after the sleep timer ended, it will release all resources.

**Comment by allmynamesweretakenomoreideas** [comment] 2016-03-11 22:07
I get a message box with "Material player quit" with the options "report" and "OK". I just reproduced it and sent the report.

**Comment by PaulWoitaschek** [comment] 2016-03-11 22:14
* Which version are you using? 
* Is this 100% reproducible? 
* Did you enable crash reports in the settings?

**Comment by allmynamesweretakenomoreideas** [comment] 2016-03-12 08:12
- Version 2.6.0.1
- yes, rebootet and tried again. Report just sent.
- yes, enabled

**Comment by PaulWoitaschek** [comment] 2016-03-12 08:56
Please make sure to always use the latest version when reporting a bug. (2.6.0.5)

**Comment by PaulWoitaschek** [comment] 2016-03-17 22:51
Closing for now. If this is still an issue please comment.

**Closed by PaulWoitaschek** 2016-03-17 22:51 UTC
