### ISSUE TITLE
MAP continues playing despite alarm / incoming call

### ISSUE THREAD

**Issue by hackabytegithub** [PaulWoitaschek/MaterialAudiobookPlayer#436] opened 2016-03-25 07:50 UTC
In the latest version 2.7 (and at least 1 or 2 versions prior ~ sorry for being vague as I do not recall), when a scheduled alarm is going off or an incoming call is ringing, MAP continues to play without pausing at the same volume. The Preference is set to pause on interruption. I have tried clearing the data/cache as well as uninstall/reinstall but the behaviour persists despite the setting in Preferences.

I have reverted to version 2.5.1, an old version that is already on my phone and it is working as expected.

Samsung Note 3 SM-N9005 on Android 5.0

**Comment by karpach** [comment] 2016-03-26 03:15
I am seeing this issue as well.

**Comment by PaulWoitaschek** [comment] 2016-04-20 21:01
I can't reproduce this.

Can you describe exactly what you do?
When I play a book and an alarm comes in, the player pauses correctly for me.

**Comment by hackabytegithub** [comment] 2016-04-21 12:20
Ok, I will try.

 

I would just upgrade using the Play Store.

I would run the program,

select a single folder for my audiobooks,

choose the dark theme,

enable report bugs,

disable resume playback,

enable pause on interruption,

set the skip amount to 30 seconds,

enable to bookmark on sleep,

set the auto rewind to 5 seconds,

then start listening to any audiobook.

 

When a preset alarm goes off (starts ringing), MAP will continue playing in the background while the alarm rings.

 

If I missed anything, please let me know.

**Comment by PaulWoitaschek** [comment] 2016-04-21 18:10
Still can't confirm this.

Is this what you did?

https://youtu.be/c-7wkQjZ2iQ

And at the point where the alarm went off the player just continued? oO

**Comment by hackabytegithub** [comment] 2016-04-22 05:51
Yes, this is pretty much what I did, except I don’t wait for the alarm to ring. Usually I’m just listening with the screen locked and when the alarm starts going off, the player just continues right on.

 

Unfortunately, I’ve very recently switched phones (not because of this bug though :P ) and I’m not able to test this further for you. On this phone, running 6.0.1, the latest version 2.7.2.1 seems to work properly. It appears that some other people have the same experience. Perhaps it is specific to the Samsung Note 3 running 5.0?

**Comment by mrsb33** [comment] 2016-05-22 20:22
I have also been having this issue since first installing. My alarms do not seem to be affected, but OCCASIONALLY the player will continue to play when I answer a call and/or will close completely after call is ended, forcing a restart of the player. 

The non-pause only occurs while using my Bluetooth device, but the complete stop occurs randomly, whether using Bluetooth, headphone plug or neither. Since these issues are only occasional, I cannot recreate them, but will try to note some specifics the next time either issue occurs.

Samsung Note 3 SM-N900V on Android 5.0

**Comment by hackabytegithub** [comment] 2016-05-23 08:45
As a matter of fact, I experienced this several times on my new phone, i.e. the player could continue to play in the background while I answered a call and am talking to the other party, so I would manually stop the player to continue my conversation with better clarity.

 

Samsung S7 Edge SM-G935FD on Android 6.0.1

**Comment by nitro322** [comment] 2016-06-08 20:26
Just FYI, I've run into this issue as well.  It only happens sometimes, not all of the time.  It's always happened for me when I'm listening via bluetooth and I answer an incoming call - again, though, only sometimes.  I haven't been able to figure out any particular pattern, but now that I know it's affecting other people I'll try to figure out some way to reproduce.

**Comment by mrsb33** [comment] 2016-12-28 22:20
Update: I now have a new phone: Samsung Edge 7 (SM-G935V) running Android 6.0.1 and what used to be an occasional problem is nearly constant. What's even worse, the volume of the player increases when I connect to a call and I have to tell my caller to hold on while I navigate around to pause. They can hear the audio in the background. I basically won't use the player now when expecting an important call. It's no biggie with family, but terribly embarrassing for business calls. PLEASE FIND A FIX FOR THIS!!

**Comment by PaulWoitaschek** [comment] 2016-12-29 09:49
I'm not sure how to adress it. It looks very much like another strange samsung bug, so without a samsung phone its quite hard to debug.

**Comment by kettelarij** [comment] 2017-02-16 12:57
its not a Samsung only problem, using Huawei P9, same thing occasionally happens to me.

**Comment by PaulWoitaschek** [comment] 2017-03-01 20:47
I was able to reproduce this today.

Can you test version [3.0.8](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v3.0.8) and report if the issue is fixed for you?

**Comment by PaulWoitaschek** [comment] 2017-03-10 19:15
I assume this is fixed. If not please comment and I'll reopen immediately.

**Closed by PaulWoitaschek** 2017-03-10 19:15 UTC
Labels: Bug, PR welcome
