### ISSUE TITLE
Audio position erratically changing

### ISSUE THREAD

**Issue by brad** [PaulWoitaschek/MaterialAudiobookPlayer#385] opened 2016-01-01 16:18 UTC
I'm not quite sure how to describe this issue since it's a little bit random. Every time I try to change the position in the track (skipping ahead/back) or pause/play it doesn't end up where expected. Example: I just pressed pause, then play, and the track jumped forward about 30 seconds. That's not always what it does though, sometimes it jumps backward. It's unpredictable.
Nexus 6
Android 6.0.1

**Comment by PaulWoitaschek** [comment] 2016-01-01 16:34
Which version are you using? Is this happening with all files?

**Comment by brad** [comment] 2016-01-01 18:57
Sorry Paul, I forgot to mention that. I was seeing it with the latest version in the store, then I came here and got 2.5.0.5 and I also am seeing the problem there.

**Comment by PaulWoitaschek** [comment] 2016-01-04 18:22
Weird. Does this happen to all audio files? Looks like corruption to me.

**Comment by brad** [comment] 2016-01-04 19:43
@PaulWoitaschek Shoot, I think you must be right, but.... they play correctly in "Smart AudioBook Player". I'm only seeing the issue in books I have extracted from CDs, I guess I must have messed up somewhere. I'll take a closer look and see if the meta data on the mp3s looks correct.

**Comment by brad** [comment] 2016-01-04 20:10
Here is a single file from a failing book. I can reproduce the problem there.
[GGS.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/77631/GGS.zip)

**Comment by brad** [comment] 2016-01-05 17:18
I ran the files through EasyTag, and didn't notice anything obviously awry. It made some automatic modifications and I tried again after saving those, but it didn't seem to make a difference (I still get erratic position changes)

**Comment by bitinerant** [comment] 2016-01-22 08:26
I have a lot of .ogg files which do not work correctly in Material Player in the way described above--the position changing unpredictably on seek or resume.  It wasn't until yesterday that I wiped my database to investigate this problem and concluded that it had nothing to do with the other books in my database.  It is something about the particular files.  I am certain of this problem on both 2.4.2.2 and 2.5.0.8, but I believe it has been an issue since before 2.4.2.2.  I am running CM12.

A simple way to reproduce this issue is to open the attached file with MP.  Then, with the file paused, move the position to somewhere in the middle.  Note the position in minutes and seconds, tap play, wait a second or so, tap pause, then note the position again.  In this particular test, it seems to jump backwards 60-120 seconds, but in other situations it is more.  Similar problems occur when changing the position.  (My "Auto rewind" config is set at 7 seconds.)

I attached one of the problem .ogg files.  Both Totem and VLC on Ubuntu show the file length to be 33m12s and play and seek normally.  Material Player, however, shows the file length as 36m28s.  Interestingly, if you play it from start to finish in MP, it plays just fine but stops at 33m12s.  (The file is compressed from a .wav file using avconv with options "-codec:a libvorbis -qscale 1".)

[Slashdot to read 2016-01-21.ogg.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/100467/Slashdot.to.read.2016-01-21.ogg.zip)

**Comment by bitinerant** [comment] 2016-01-28 20:53
Here is some additional information.  If I encode the .wav file (different file than uploaded above) with avconv options "-codec:a libvorbis -qscale 1", MP shows the length as 26m04s, stops playing at 23m41s, and jumps backwards 70-90 seconds on each play/pause sequence.  If I encode the same .wav file with "-codec:a libvorbis -b 64k", i.e. NOT VBR (variable bit rate), everything is better--the displayed length is 24m15s, stops playing at 23m41s (same), and only jumps backwards 13-19 seconds on each play/pause sequence (it should jump back 7 seconds per "Auto rewind").  I thought not using VBR would completely get around this issue, and it helps a lot, but there is still a bug where the file length is not computed correctly and a related seek issue.  By the way, in Totem, both .ogg files work fine and display the total length as 23m41s.

**Comment by bitinerant** [comment] 2016-02-16 13:45
@PaulWoitaschek I have sadly stopped listening to my TTS books because it is so painful to pause in the middle.  What is your take on this bug?  I don't think it's a corrupted file because it happens on all of the .ogg files I convert from .wav (unless it's a bug in avconv).  I am willing to do further testing if it would help.

**Comment by bitinerant** [comment] 2016-02-27 11:47
I saw that #386 was fixed in 2.6.0.1 and decided to retest #385, but unfortunately no--it still jumps backwards a couple of minutes when I resume.

**Comment by bitinerant** [comment] 2016-03-05 18:54
Here is a public podcast that, when played in Material Player 2.6.0.1, seek does not work at all:  [ubuntupodcast_s09e01.ogg](http://static.ubuntupodcast.org/ubuntupodcast/s09/e01/ubuntupodcast_s09e01.ogg).  I suspect it is a related issue.

**Comment by bitinerant** [comment] 2016-03-06 08:11
I updated to 2.6.0.4 and the above-mentioned podcast continues to have the same problem.  It plays fine, even at a faster speed, and you can pause and resume playback.  However, when you try to change position within the file--either by tapping on the progress control or by tapping the forward or back buttons--it jumps there and then immediately back to where you were before.

**Comment by nioncode** [comment] 2016-10-15 10:28
I observe a similar issue with an .opus file that I converted from m4a with:
```ffmpeg -i in.m4a -codec:a opus -b:a 32k out.opus```
It's an audiobook with 4.5 hours length and when I try to seek to a specific position, it is always off by a couple of seconds and a play-pause-play sequence seeks a couple of seconds forwards.

This is really annoying, since opus would be a great format with less storage cost for audiobooks.

**Comment by bitinerant** [comment] 2016-10-15 10:56
I, too, continue to have this issue.  I'm now on 2.7.2.3 from F-Droid.

**Comment by nioncode** [comment] 2016-10-20 05:53
I just hacked out a demo application which just uses Android's MediaPlayer API to play a long opus file.
The same bug happens there, so it seems to be an upstream issue.
I'm going to try this with the Android 7.1 Developer Preview soon.

**Comment by PaulWoitaschek** [comment] 2016-11-04 08:06
Closed as upstream, thanks.

**Closed by PaulWoitaschek** 2016-11-04 08:06 UTC
Labels: Waiting for User

**Comment by brad** [comment] 2016-11-05 01:20
@PaulWoitaschek FWIW I'm no longer experiencing this issue on Android 7.1.1

**Comment by nioncode** [comment] 2017-05-06 15:23
Since 3.3.1 and ExoPlayer's opus extension, opening and seeking a large opus file works very smoothly during my first tests.
