### ISSUE TITLE
Bug: Media sound 1 point increases on next track

### ISSUE THREAD

**Issue by zealotsinstc** [PaulWoitaschek/MaterialAudiobookPlayer#346] opened 2015-11-10 11:08 UTC
Hello!

Faced an issue on my Samsung Galaxy Note 4 (Lollipop 5.1.1): android media sound value is increased 1 dimension on next track (both automatic next track playback or manual rewind - doesn't matter).
I'm currently listening to audio book with many 1-4 minute files, it's very irritating :)

Thank you!

**Comment by skynetua** [comment] 2015-11-10 11:21
Duplicate of #343. I was able to reproduce this issue on few other samsung devices only. Looks like it's  some kind of manufacturer related problems.

**Comment by zealotsinstc** [comment] 2015-11-10 11:25
Look like that. At the time I don't reproduce this issue on other players (Deadbeef or Mort player) on this device.

Thank you for the reply!

**Comment by zealotsinstc** [comment] 2015-11-22 20:24
I've noticed that "play/pause" case has this issue as well. So it looks like this issue is about "play" function implementation, not the "next track" case.

**Comment by Ph1b** [comment] 2015-11-22 21:10
Can you check if this is fixed for youin the [latest nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-2015-11-22)

**Comment by zealotsinstc** [comment] 2015-11-23 21:46
Just checked it - no, unfortunately it isn't. I still got sound increase clicking play/pause :(

**Comment by PaulWoitaschek** [comment] 2015-12-16 08:31
Still happens in 2.4.4?

**Comment by zealotsinstc** [comment] 2015-12-16 13:15
Just checked - yes, still happens :(
BTW it also crashed on startup after update from 2.4.2 to 2.4.4, only clean install worked out.

**Comment by zealotsinstc** [comment] 2016-02-10 12:56
This issue is killing me :(

**Comment by PaulWoitaschek** [comment] 2016-02-10 18:41
Can someone who as a device that makes the problem reproducable have a look on what is going on here? Some logs would be enlightening.

**Comment by zealotsinstc** [comment] 2016-02-13 16:56
Paul, may be I can be a use for you? I'm not able to debug the stuff, however I can send you any log files you need, or anything else :)

**Comment by PaulWoitaschek** [comment] 2016-02-13 17:08
Can you set up [ADB](https://developer.android.com/tools/help/adb.html)? Or is your phone even rooted? Then we can go with [Catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=de) for logs).

**Comment by PaulWoitaschek** [comment] 2016-02-14 12:12
I made a version for you that stores the logs. Please install it, press the keys till the volume increased to max. Then go to the main menu, click on top right and press `send logs`.
That will open your email client with the logs prefilled.

https://www.dropbox.com/s/kz6w9h6i9u4h52a/106-preview-audiobook-debug.apk?dl=0

**Comment by zealotsinstc** [comment] 2016-02-14 13:19
Hi!

Here is your log file, take a look: 
[16.txt](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/129666/16.txt)

I've pressed a lot of keys here, so here are my notes:

At first I've started the app, set a books folder to David Rose book. Then I messed a bit with pressing play/pause, but found out that volume was max already. Then I've set volume to zero, and pressed play/pause until the volume got max. Then I've set volume to zero again and started chaoticly to press next/previous track buttons and the app has crashed. I've restarted it and repeated test with play/pause. Then I've suссessfully made the test with next/previous track buttons to max from zero volume. And then I've checked if rewind buttons have this effect - they did not, but again as I stress tested the app has stopped working.
I never pressed volume-up button durig the test on my smartphone, only making the volume down (I might just accedently hit it once).

Paul, if this all looks confusing in logs I can record a video from my smartphone if you like (however it would take some more time as I need to find the right soft for that).

Thank you so much for addressing this issue.
I'll follow this thread just in case if you need anything else.

**Closed** 2016-02-15 12:41 UTC
Labels: more information needed

**Comment by zealotsinstc** [comment] 2016-02-16 12:42
Paul,
Have you been able to resolve the problem? Are you planning to include this update to 2.5.2 version?
Thanks!

**Comment by PaulWoitaschek** [comment] 2016-02-16 17:51
This is included in the latest version which is so far pushed to 20% of the user base.

**Comment by zealotsinstc** [comment] 2016-02-16 23:09
Wow, amazing! Thank you!

**Comment by zealotsinstc** [comment] 2016-02-18 18:14
Hi,

Just want to let you know that as soon as I updated the app its occurred that issue no longer relevant,  all works fine. However app began crashes pretty frequently (around 15-20 times for the past 2 days) on various moments, but most often during switching a view: from some audio book to books list, or after minimizing the app, sending it to background.
If you need I can provide a log. My phone is rooted just tell me where I can find the files you need.

Thanks!
