### ISSUE TITLE
Suggestion: remember position in each book file not fully listened.

### ISSUE THREAD

**Issue by zealotsinstc** [PaulWoitaschek/MaterialAudiobookPlayer#340] opened 2015-10-23 05:40 UTC
Hello Team! Thank you for this amazing player, that is exactly what I was searching for!

There is one feature that exists in some other players and I'm lacking it with Material player. I think would be very useful for everybody. This is: 
<b>Remembering position in each audiobook file that was not fully played.</b>
Consider these use cases:
1. User accidently presses next track button: when he press back listening position is lost.
2. Book constains references to other chapters within it (for example some study course). Remembering position would allow easy navigation during the listening. Even if you want to navigate within book by your own reason, for example to re-listen some previous chapters.

I face both these use cases in my everyday usage.
Thank you and Good luck!

**Comment by NeuroNex** [comment] 2015-10-27 00:48
+1. In my opinion, this is a must have feature for Audiobook player. On unabridged audiobook (a multi hours single file) this feature is not big of a deal. But on audiobooks which are carefully chapterized in multiple files. Remember the position of the unfinished file/track increases significantly the comfort and the reliability of the player.

**Comment by nvx2004** [comment] 2015-11-28 11:40
+1 Yes please, that would be very nice.

**Comment by kevmitch** [comment] 2015-11-28 13:23
duplicate of  #224

**Closed** 2016-02-17 09:07 UTC
