### ISSUE TITLE
Feature Request: Shake detection to reset sleep timer

### ISSUE THREAD

**Issue by allmynamesweretakenomoreideas** [PaulWoitaschek/MaterialAudiobookPlayer#429] opened 2016-03-11 21:16 UTC
Note: This request makes sense when Request #428 is implemented. When sleep timer runs up and the volume is fading the listener is able to take immediate action to prevent turning off the audio book by shaking the device. Without looking at the device or even open the eyes. Sleep timer will be reset and begin count down again.

**Comment by kevmitch** [comment] 2016-03-11 21:35
duplicate of #407

**Closed** 2016-03-11 21:53 UTC
