### ISSUE TITLE
Some mp3 files play too fast when no speed adjustments been made (speed=1)

### ISSUE THREAD

**Issue by igormisha** [PaulWoitaschek/MaterialAudiobookPlayer#129] opened 2015-02-04 13:44 UTC
I installed 1.5.3 version of application from google.play service on my android phone and tried to play some mp3 files with and without speed adjustments, for some of them everything works ok, but others play not correctly (much faster than it should be, like it is been forward winded) even if speed isn't touched (speed=1).

I also checked wrong played tracks on other mediaplayer app and they were played at normal speed (correctly).

**Comment by Ph1b** [comment] 2015-02-06 17:49
At the moment the app just remembers the last speed and applys them till you change the speed again. Could that be the problem? I changed it yesterday so that the time will be remembered for each book individually, but the way it behaves now could have caused the confusion?

**Comment by igormisha** [comment] 2015-02-07 07:43
Hello, Paul! No, I checked one more time the speed, it is set to 1.00, and some mp3 play at normal speed and some play much faster, much more than 2 times faster, it is something with decoding seems.

**Comment by Ph1b** [comment] 2015-02-07 09:34
And is it reproducible? Is it always the same file?

**Comment by igormisha** [comment] 2015-02-07 11:58
Yes, the behavior is always the same. This is not only one file, this is happening with several of my audiobooks. And I checked that other player plays them well. I could send you one of such badly played mp3 files for testing by mail as an example if you wish.

**Comment by igormisha** [comment] 2015-02-07 13:02
I've made more testing measuring time played and it appeares that speed for badly played tracks is doubled compare to normal, though it's set to 1.00 value in player settings.

**Comment by Ph1b** [comment] 2015-02-07 13:38
Yeah, please send me a file to woitaschek@gmail.com

Thanks,
Paul

**Comment by igormisha** [comment] 2015-02-07 14:12
I've sent you one mp3 file, also I made some more looking into this and at least for some of files which cause problems they all have 1 channel and 32 bitrate. And other mp3, which don't cause any problems have 2 channels and 32 bitrate. May be this will help. I didn't check all files though.

**Comment by Ph1b** [comment] 2015-02-07 15:54
I cant reproduce this one, so I dont really know, where to fix it. Maybe someone with more knowledge can look into this?

**Comment by dreamdt** [comment] 2015-02-07 17:53
I have the same problem. Downgrade to 1.4.6.1 solved problem for me.

**Comment by Ph1b** [comment] 2015-02-07 17:55
What happens on 1.4.6.1 if you install Prestissimo?

**Comment by dreamdt** [comment] 2015-02-07 18:13
No difference with installed Prestissimo. 1.4.6.1 works correct, 1.5.3 does not.

**Comment by hub2git** [comment] 2015-02-17 04:09
I also have this problem. MP3 files play fast and with a chipmunk voice, even when speed is left at the default of 1.0X speed.The same files play nicely when using another audio app.

**Comment by Ph1b** [comment] 2015-03-18 03:28
Which smartphones do you use? I assume it is still present in latest nightly? https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418

I read a lot about bugs on certain devices like the Fairphone and anotherone with the same chipset. If so, I could default to the default Android MediaPlayer. That would mean stability, but no speed adjustments.

**Comment by hub2git** [comment] 2015-03-19 00:58
ph1b,
I use MyPhone Agua Rain 2G.

**Comment by Ph1b** [comment] 2015-04-11 00:27
I just wrote a small diagnostic app printing device info. https://www.dropbox.com/s/catp8qgwuvmbosi/app-debug.apk?dl=0
Can you post here, whats on the screen? I made it selectable so you should be able to copy paste it:
![screenshot_2015-04-11-02-26-37](https://cloud.githubusercontent.com/assets/743462/7099396/3cdf79fc-dff2-11e4-9546-6c43436d2137.png)

My idea is to blacklist the buggy devices so they use the android media player.

**Comment by igormisha** [comment] 2015-04-11 14:04
cpuAbi1=armeabi-v7a
cpuAbi2=armeabi
device=Lenovo
model=N903
product=Lenovo
hardware=mt6582

abi: armeabi-v7a
Processor : ARMv7 Processor rev 3 (v7l)
processor : 0
BogoMIPS: 2590.72

processor: 1
BogoMIPS: 2590.72

processor: 2
BogoMIPS: 2590.72

Features: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt
CPU implementer: 0x41
CPU architecture:  7
CPU variant:          0x0
CPU part:               0xc07
CPU revision:         3

Hardware: MTK6592
Revision: 0000
Serial: 0000000000000000

**Comment by dreamdt** [comment] 2015-04-12 18:52
Hello, i just made some research with a player code. Speed bug appears with incorrect channels count, when codec gets it after MediaCodec.INFO_OUTPUT_FORMAT_CHANGED.
But extractor returns correct value. This patch fixes problem for me. I have no idea if it's a correct way, but it works with mono and stereo files too.
Anyway, this should be tested.
https://dl.dropboxusercontent.com/u/1830638/speed_bug_workaround.patch
(sorry, i dont know how to do pull requests)

**Comment by igormisha** [comment] 2015-04-13 09:00
@ dreamdt:
Could you upload also patched apk to test on my device?

**Comment by dreamdt** [comment] 2015-04-13 09:37
Sure, but make backup before using it 
https://dl.dropboxusercontent.com/u/1830638/audiobook-debug-speed-fix.apk

**Comment by Ph1b** [comment] 2015-04-15 13:11
How is it going?

**Comment by igormisha** [comment] 2015-04-15 13:29
Well, I installed patched apk file and everything works as expected for now, may be there will be error later at sertain sircumstances though.

**Comment by igormisha** [comment] 2015-04-15 13:50
I'm not java man, but I had a look into patch and it seems strange to me, because current code in repository reacts to condition INFO_OUTPUT_FORMAT_CHANGED and reinitializes device with both new parameters (sample rate and channel count) taken from reloaded MediaFormat oformat. And with this patch device is reinitialized with updated only one parameter and the second is given old value.

**Comment by dreamdt** [comment] 2015-04-15 18:13
My tablet hardware

cpuAbi1=armeabi-v7a
cpuAbi2=armeabi
device=ME173X
model=ME173X
product=RUS_memo
hardware=mt8125

abi: armeabi-v7a
Processor	: ARMv7 Processor rev 2 (v7l)
processor	: 0
BogoMIPS	: 1521.68

processor	: 1
BogoMIPS	: 1526.68

processor	: 2
BogoMIPS	: 1526.68

processor	: 3
BogoMIPS	: 1526.68

Features	: swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 2

Hardware	: MT8125
Revision	: 0000
Serial		: 0000000000000000

**Comment by Ridderby** [comment] 2015-04-24 19:50
Hi, 
I have experienced same problem with very high speed of book reading. I'd like to confirm that the patched version works well for me with the same book and files. 

Just to clarify it works less fine when opening a book, it opens one book per file.

**Comment by Ph1b** [comment] 2015-04-24 20:49
> Just to clarify it works less fine when opening a book, it opens one book per file.

What do you mean by that?

**Comment by Ridderby** [comment] 2015-04-24 20:52
When I chose a folder to contain one book and the folder contains 100 files (one file very 5 minute) the patched version opens 100 books; CD 1 - Tack 01, CD 1 - Track 02 etc. 
Just wanted to mention this because the released player works just fine from this aspect and I like to keep it that way.

**Comment by dreamdt** [comment] 2015-04-25 10:00
Hello. I made an update to patched version with latest sources.
https://dl.dropboxusercontent.com/u/1830638/audiobook-debug-speed-fix.apk

>When I chose a folder to contain one book and the folder contains 100 files (one file very 5 minute) >the patched version opens 100 books; CD 1 - Tack 01, CD 1 - Track 02 etc.
Is problem still exists?

**Comment by Ridderby** [comment] 2015-04-25 11:53
>Hello. I made an update to patched version with latest sources.
>https://dl.dropboxusercontent.com/u/1830638/audiobook-debug-speed-fix.apk
>Is problem still exists?

Thanks, it seems to work fine now.

**Comment by tobika** [comment] 2015-05-06 12:52
can also confirm the fix works fine until now
Info: I'm using a Fairphone

thanks for the great player and the fix

**Comment by Ph1b** [comment] 2015-05-24 16:34
Does it work with [this version](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/distribute/v2.1.8-pre1-debug.apk)?

**Comment by tobika** [comment] 2015-05-24 21:09
@Ph1b : thank you, for me it works great.

What I tested: 
- Adding folder with audiobooks
- Listening to mp3s that had the speed problem before, now they play correctly
- Changing settings

**Comment by Ph1b** [comment] 2015-05-24 21:29
I got the channel count from the AudioTrack, but I do not fully understand what that means and what the sideeffects are in general. Has someone a file where the format changes so we can see what happens? a736b0fe471015a4e113da432fe36d3466de3afa

**Comment by Ph1b** [comment] 2015-05-26 00:50
(finally) fixed as of 129694928f6b6bbf2cb837a6e51c0651f8be8bed.

**Comment by Ph1b** [comment] 2015-06-02 23:07
This is reverted for now since it causes many problems on before correctly working files. Current solution is gathering data for blacklisting.

**Comment by Marxsal** [comment] 2015-06-03 01:17
My problem was that versions 2.1.8 and 2.1.9 made some audio files play slow & low.

V 2.1.7 does appear to work  so far.

Note again about the debug tool: After selecting the onscreen text, there is NO icon in the upper right hand to allow copying the text as one would expect.

----

Android 4.2.2, Samsung SM-T310.

**Comment by msjoberg** [comment] 2015-08-25 17:01
I have the exact same problem on my Fairphone. Using version 2.1.8-pre1 seems to play them fine, but then I miss out on all the improvements in newer version of Material Player.

**Comment by Ph1b** [comment] 2015-08-25 18:10
Could you both please post the output of [this tool](https://www.dropbox.com/s/n8sx7gnvh0zab3q/device-info.apk?dl=0)?

**Comment by nkuznetsow** [comment] 2015-08-25 18:15
Unfortunately, using channel count from MediaExtractor cause opposite problem on some Samsung devices.

As you know, on some devices MediaCodec sets in output format wrong channel count (real is 1 channel, it set 2 channels). But raw audio data contains only one channel. If you try to play this audio data on AudioTrack with two channels it will plays fast.
There are some devices, that also returns channel count not match extractor (1 channel in extractor, 2 channels in output format), but on this devices raw audio data contains TWO channels! And when you will try to play this audio data on AudioTrack with channels count from extractor format it will be playing SLOW!

It applicable for: 
samsung gt-i9300  api 18
samsung gt-n7100 api 18

maybe other devices.

I try to solve it a few days, but still no results.

I think it affects all apps which uses MediaCodec.

**Comment by msjoberg** [comment] 2015-08-25 18:17
```
cpuAbi1=armeabi-v7a
cpuAbi2=armeabi
device=FP1
model=FP1U
product=FP1
hardware=mt6589

abi: armeabi-v7a
Processor       : ARMv7 Processor rev 2 (v7l)
processor       : 0
BogoMIPS        : 2439.94

processor       : 1
BogoMIPS        : 2447.96

Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 2

Hardware        : MT6589
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by msjoberg** [comment] 2015-08-25 18:22
BTW, as a temporary work-around I have found that converting the one channel file to two channels fixes the problem for me. E.g. like this:

    avconv -i old.mp3 -c:v copy -ac 2 new.mp3

**Comment by Ph1b** [comment] 2015-08-25 18:24
Blacklisted the fpu device:
b3925e2563230dc1fa086ac6135aa77a4d0e04e5

Seems we have our first double-match:
mt6589

**Comment by Ph1b** [comment] 2015-09-08 18:22
I had a conversation with Mulong Chen, the developer of [realm.io](https://realm.io/) and we came up with the solution to have a single mini file as asset which has the changing channel count. That one we can use to check on first usage if the device should be blacklisted or not.

Can someone create such a file with changing channel count?

**Comment by nkuznetsow** [comment] 2015-09-09 05:50
This file unable to resolve this problem completely. On some devices, decoder increases output channel and also increases output audio data. It must be played with decoder channel count instead of extractor channel count. I have wrote it above.

File says you that output channels count not match extractor channels count, but you don't know how to play output data: with extractor channels count or with decoder channels count.

I see two ways to resolve it:

1) write own mp3 decoder based on open source c++ library like mpg123 http://www.mpg123.de/
2) collect device list, which must plays decoder output data with decoder output channels count.

I use second way. Now in my list has next devices:

samsung_gt-i9300_18
samsung_gt-n7100_18
samsung_gt-n7000_16
samsung_gt-i9105p_17
samsung_gt-i9100_16
samsung_gt-p3110_17

Maybe you have another opinion?

**Comment by dreamdt** [comment] 2015-09-09 06:55
I think, vlc player somehow handles this problem. It plays mono/stereo/multichannel files on my device  correctly, using AudioTrack.

**Comment by igormisha** [comment] 2015-09-09 09:36
> I had a conversation with @beeender, the developer of realm.io and we came up with the solution to have a single mini file as asset which has the changing channel count. That one we can use to check on first usage if the device should be blacklisted or not.
> -Ph1b

That's what I thought of, and even started coding my decision, but I had a little better idea - not to blacklist such devices but instead adapt channel counting algorithm while decoding process. For devices which's mediacodec show fake message that it changed format when it actually didn't we take the channel count got by mediaextractor (into this category fall devices you blacklisted, including mine, and I don't like this :) ). Otherwise we use channel count provided by mediacodec (standart currently working algorithm). What do you, people, think?

**Comment by igormisha** [comment] 2015-09-09 10:11
@nkuznetsow : When the application first run we can decode demo.mp3 file from assets folder with 1 channel (if we get into FORMAT_CHANGED close and mediacodec gives channel_count=2) and we can count the output bytes number of decoded stream and find out is this (1 * SAMPLE_RATE * demoAudioDurationInSeconds) or (2 * SAMPLE_RATE * demoAudioDurationInSeconds). In first case this device is considered as "bad" and otherwise it is "normal". For "bad" devices while playback we get channel_count through mediaextractor, for others through mediacodec.

**Comment by nkuznetsow** [comment] 2015-09-09 10:14
@igormisha, I think it will work! I try to implement it in my app today.

**Comment by igormisha** [comment] 2015-09-09 10:26
I've made file about 10sec with 1 channel.

**Comment by Ph1b** [comment] 2015-09-19 20:49
Are you willing to implement this and submit a pull request?

**Comment by LordJordane** [comment] 2015-11-01 09:30
Galaxy Note 4 N910C( treltexx):
cpuAbi1=armeabi-v7a
cpuAbi2=armeabi
device=treltexx
model=SM-N910C
product=treltexx
hardware=universal5433

abi: armeabi-v7a
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 52.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 1

processor	: 1
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 52.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 1

processor	: 2
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 52.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 1

processor	: 3
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 52.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 1

processor	: 4
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 40.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 0

processor	: 5
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 40.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 0

processor	: 6
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 40.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 0

processor	: 7
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 40.00
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 0

Hardware	: Samsung EXYNOS5433
Revision	: 0015
Serial		: 27a157e4443b0041

I'm more than willing to live without playback speed customization. This bug has really rendered the app unusable for me,

**Comment by PaulWoitaschek** [comment] 2016-01-04 21:17
I started working on detecting if the device is errorous.

[**Branch**](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/tree/feature/audio_channel_bug_detection)

The manipulated track is 1s of mono then 1s of stereo merged by a simple `cat *.mp3 > joined.mp3`
However I don't know how to feed the track with the correct data so he is able to report the updated channel count.
The important line is [here](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/510fc2bd97cfd91a910feb30c3aa6b10fe10ea36/audiobook/src/main/kotlin/de/ph1b/audiobook/playback/FalseChannelDetector.kt#L82). If someone can look into it that would be great.

**Comment by igormisha** [comment] 2016-01-05 07:36
Hi, Paul, why do you need to create AudioTrack? I think there is no reason to play the audio, you just need to decode this mono-channel 1sec audio with MediaCodec and count number of bytes it provides you. If codec issues MediaCodec.INFO_OUTPUT_FORMAT_CHANGED and shows channel count is changed, then start counting bytes and check if number of bytes is really changed (doubled), i.e.  2*sampleRate*bytesPerSample (for example, 2 * 44100 * 2), then the device works normal, else the device fakes the change of channels number.

**Comment by igormisha** [comment] 2016-01-05 08:10
By the way, I'm not sure, but it's possible that codec may change not only channel count but sample rate as well. For example we feed the mono channel 44100 bps mp3 audio to codec but device has hardware with 2 channels and it plays 48000 bps. In such case codec may issue INFO_OUTPUT_FORMAT_CHANGED and show you that output streem will be 2 channel and 48000 sample rate (outputFormat = codec.getOutputFormat()). So, if it does not lie, then the number of bytes for 1sec audio 16pcm should be 2 * 48000 * 2. 
I didn't check though with different number of samples per second audio on my phone.

**Comment by igormisha** [comment] 2016-01-05 09:26
To elaborate a little on what I mean:
=================
```java
class FalseChannelCount {
    MediaExtractor extractor = new MediaExtractor();
    extractor.setDataSource(path);
    MediaFormat oFormat = extractor.getTrackFormat(0);
    int sampleRate = oFormat.getInteger(MediaFormat.KEY_SAMPLE_RATE);
    int channelCount = oFormat.getInteger(MediaFormat.KEY_CHANNEL_COUNT);
    Log.d("FalseChannelDetector", "MediaExtractor sample rate = " + sampleRate); 
    Log.d("FalseChannelDetector", "MediaExtractor channel count = " + channelCount);
    int codecSampleRate;
    int codecChannelCount; 
    String mime = oFormat.getString(MediaFormat.KEY_MIME);
    long duration = oFormat.getLong(MediaFormat.KEY_DURATION);
    extractor.selectTrack(trackNum);
    codec = MediaCodec.createDecoderByType(mime);
    codec.configure(oFormat, null, null, 0);
    long bytesCount = 0L;
    boolean falseChannelCount = false;
    Runnable decoderRunnable = new Runnable() {
        @Override
        public void run() {
            codec.start();
            @SuppressWarnings("deprecation") ByteBuffer[] inputBuffers = codec.getInputBuffers();
            @SuppressWarnings("deprecation") ByteBuffer[] outputBuffers = codec.getOutputBuffers();
            boolean sawInputEOS = false;
            boolean sawOutputEOS = false;
            while (!sawInputEOS && !sawOutputEOS) {

                int inputBufIndex = codec.dequeueInputBuffer(200);
                if (inputBufIndex >= 0) {
                    ByteBuffer dstBuf = inputBuffers[inputBufIndex];
                    int sampleSize = extractor.readSampleData(dstBuf, 0);
                    long presentationTimeUs = 0;
                    if (sampleSize < 0) {
                        sawInputEOS = true;
                        sampleSize = 0;
                    } else {
                        presentationTimeUs = extractor.getSampleTime();
                    }
                    codec.queueInputBuffer(
                            inputBufIndex,
                            0,
                            sampleSize,
                            presentationTimeUs,
                            sawInputEOS ? MediaCodec.BUFFER_FLAG_END_OF_STREAM : 0);
                    if (!sawInputEOS) {
                        extractor.advance();
                    }
                }
                final MediaCodec.BufferInfo info = new MediaCodec.BufferInfo();
                byte[] modifiedSamples = new byte[info.size];
                int res;
                //noinspection deprecation
                do {
                    res = codec.dequeueOutputBuffer(info, 200);
                    if (res >= 0) {
                        final byte[] chunk = new byte[info.size];
                        outputBuffers[res].get(chunk);
                        outputBuffers[res].clear();
                        if (chunk.length > 0) {
                            bytesCount += chunk.length;
                        }
                        codec.releaseOutputBuffer(res, false);
                        if ((info.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0) {
                            sawOutputEOS = true;
                        }
                    } else //noinspection deprecation
                        if (res == MediaCodec.INFO_OUTPUT_BUFFERS_CHANGED) {
                            //noinspection deprecation
                            outputBuffers = codec.getOutputBuffers();
                        } else if (res == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {

                            final MediaFormat oFormat = codec
                                    .getOutputFormat();
                            codecSampleRate = oFormat.getInteger(MediaFormat.KEY_SAMPLE_RATE);        
                            codecChannelCount = oFormat.getInteger(MediaFormat.KEY_CHANNEL_COUNT);        
                            Log.d("FalseChannelDetector", "Codec output format changed");        
                            Log.d("FalseChannelDetector", "Codec output sample rate = " + codecSampleRate);
                            Log.d("FalseChannelDetector", "Codec output channel count = " + codecChannelCount);
                            //noinspection deprecation
                            outputBuffers = codec.getOutputBuffers();

                        }
                } while (res == MediaCodec.INFO_OUTPUT_BUFFERS_CHANGED
                        || res == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED);
            }
            if ((codecSampleRate && codecChannelCount) && (countBytes != duration * codecSampleRate * codecChannelCount * 2)) {
              falseChannelCount = true;
            }
            codec.stop();
        }
    };

    void checkChannelCount() {
      new Thread(decoderRunnable).start();
    }
}
```
=====================

**Comment by PaulWoitaschek** [comment] 2016-01-05 14:58
Thanks!

I tried to implement it but there but it still does not work.
[Here is the implementation](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/fd3e1ea7568eed2cb169e6a8f354afe879a7984b/audiobook/src/main/kotlin/de/ph1b/audiobook/playback/FalseChannelDetector.kt#L143) where it logs the counted and the expected size.

But the numbers are completely false:
```log
D/FalseChannelDetector: extractorChannelCount=1, sampleRate=44100, mime=audio/mpeg, duration=992653
D/FalseChannelDetector: Codec output format changed
D/FalseChannelDetector: Codec output sample rate = 44100
D/FalseChannelDetector: Codec output channel count = 1
I/FalseChannelDetector: calculatedCount =87551994600, measuredCount=7006
```

I still don't get how this can work. The example file is just a 1s mono and a 1s stereo file merged together.  
1. Shoudn't `Codec output channel count` print 2?
2. How can the numbers match if we use the initial track count.

**Comment by igormisha** [comment] 2016-01-05 16:58
Yeah, results look strange, especially mesuredCount=7006. It is too low for 1 second of decompressed audio. It should be at least 44100 * 2.
But I was thinking about using just 1sec mono audio, not merged mono and stereo together, can you test with such audiopiece?
As for duration, I didn't took into account that it is in microseconds, that's why difference in results is so ridiculous. So, calculatedCount should be less by 1000000.

**Comment by PaulWoitaschek** [comment] 2016-01-05 17:15
With only the mono file it does not run into `INFO_OUTPUT_FORMAT_CHANGED` and thus prints 0.

**Comment by igormisha** [comment] 2016-01-05 17:31
Well, this behavior is not compatible with how my phone works. On my device when i feed mono audio file to mediacodec it gets into the INFO_OUTPUT_FORMAT_CHANGED close. Though I didn't test new version of MaterialAudiobookPlayer, I still use old patched version to work with speed change on my device, and the patch only doesn't allow mediacodec change channel count when it gets into format_changed close.

**Comment by igormisha** [comment] 2016-01-05 17:57
Paul, can you send me these two audiopieces (mono and mono+stereo) for mesurement of byteCount on my device?

**Comment by igormisha** [comment] 2016-01-05 18:02
O, I see them in the repository in assets.

**Comment by igormisha** [comment] 2016-01-05 19:53
Ok, I made some mesurement on virtual device and on my phone, using old version of your CustomMediaPlayer.java, just added bytes counting and some logging to it. The results with your mono.mp3, stereo.mp3 and joined.mp3 are as follows:
=================
On virtual device (Samsung Galaxy S3 android 4.1.1 api 16)
mono.mp3
01-05 18:48:22.597 1159-1159/? D/BytesCount: ExtractorSampleRate = 44100
01-05 18:48:22.597 1159-1159/? D/BytesCount: ExtractorChannelCount = 1
01-05 18:48:22.625 1159-1192/? D/BytesCount: Output format changed
01-05 18:48:22.625 1159-1192/? D/BytesCount: CodecSampleRate = 44100
01-05 18:48:22.625 1159-1192/? D/BytesCount: CodecChannelCount = 1
01-05 18:48:23.497 1159-1192/? D/BytesCount: BytesCount = 78336
stereo.mp3
01-05 18:50:13.145 1159-1174/? D/BytesCount: ExtractorSampleRate = 44100
01-05 18:50:13.145 1159-1174/? D/BytesCount: ExtractorChannelCount = 2
01-05 18:50:22.465 1159-1192/? D/BytesCount: Output format changed
01-05 18:50:22.465 1159-1192/? D/BytesCount: CodecSampleRate = 44100
01-05 18:50:22.465 1159-1192/? D/BytesCount: CodecChannelCount = 2
01-05 18:50:23.401 1159-1192/? D/BytesCount: BytesCount = 167868
joined.mp3
01-05 18:51:52.481 1159-1174/? D/BytesCount: ExtractorSampleRate = 44100
01-05 18:51:52.481 1159-1174/? D/BytesCount: ExtractorChannelCount = 1
01-05 18:51:55.229 1159-1192/? D/BytesCount: Output format changed
01-05 18:51:55.229 1159-1192/? D/BytesCount: CodecSampleRate = 44100
01-05 18:51:55.229 1159-1192/? D/BytesCount: CodecChannelCount = 1
01-05 18:52:02.109 1230-1230/? D/BytesCount: ExtractorSampleRate = 44100
01-05 18:52:02.109 1230-1230/? D/BytesCount: ExtractorChannelCount = 1


On my device (Lenovo N903 android 4.4.3)
mono.mp3
01-20 06:39:02.994 4169-4169/? D/BytesCount: ExtractorSampleRate = 44100
01-20 06:39:02.995 4169-4169/? D/BytesCount: ExtractorChannelCount = 1
01-20 06:39:03.279 4169-4604/? D/BytesCount: Output format changed
01-20 06:39:03.279 4169-4604/? D/BytesCount: CodecSampleRate = 44100
01-20 06:39:03.279 4169-4604/? D/BytesCount: CodecChannelCount = 2
01-20 06:39:03.893 4169-4604/? D/BytesCount: BytesCount = 66816
stereo.mp3
01-20 06:40:57.748 4169-4197/? D/BytesCount: ExtractorSampleRate = 44100
01-20 06:40:57.749 4169-4197/? D/BytesCount: ExtractorChannelCount = 2
01-20 06:41:00.047 4169-4604/? D/BytesCount: Output format changed
01-20 06:41:00.047 4169-4604/? D/BytesCount: CodecSampleRate = 44100
01-20 06:41:00.048 4169-4604/? D/BytesCount: CodecChannelCount = 2
01-20 06:41:00.516 4169-4604/? D/BytesCount: BytesCount = 133120
joined.mp3
01-20 06:43:33.102 4169-4197/? D/BytesCount: ExtractorSampleRate = 44100
01-20 06:43:33.103 4169-4197/? D/BytesCount: ExtractorChannelCount = 1
01-20 06:43:36.084 4169-4604/? D/BytesCount: Output format changed
01-20 06:43:36.084 4169-4604/? D/BytesCount: CodecSampleRate = 44100
01-20 06:43:36.084 4169-4604/? D/BytesCount: CodecChannelCount = 2
01-20 06:43:38.411 4169-4604/? D/BytesCount: BytesCount = 235008
=================

As you can see, on both devices format_changed event happened for all audiofiles, but on virtual device when mono.mp3 played there was not changed channels count and on my device channels count changed from 1 to 2. Also bytes count was different on both devices(78336 and 66816 for mono.mp3), but it was more close to normal, than what you got in your test mesuredCount = 7006.

I attach modified CustomMediaPlayer.java for you in case you need to look into it.
[CustomMediaPlayer.java.txt](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/78948/CustomMediaPlayer.java.txt)

**Comment by PaulWoitaschek** [comment] 2016-01-06 07:18
I faced something weird. On Android 6 it prints a value. (7k). On 4.3 it always prints 0.

Do you have any idea what could be going on?

**Comment by igormisha** [comment] 2016-01-06 08:47
As for your question, I have no idea for now.
The bigest thing I don't get is why the numbers of decoded bytes in my last test are different for the same file, but they don't differ by 2. If I understand correctly 16pcm audiostreem, as I'd written before, these numbers should be arround 88200 bytes (for mono) and 176400 bytes (for stereo) for 44100 samples per second sample rate. But I got 66816 bytes and 78336 bytes which is much less than expected. What do you think about this? Can you look into file I sent in my last post? Do I count all decoded bytes correctly or not?

**Comment by PaulWoitaschek** [comment] 2016-01-06 12:25
Looks fine to me. I'll dig into this later.

Can you (and others) check [this small app](https://www.dropbox.com/s/j0g65flepx8tb07/app-debug.apk?dl=0) and report me what it prints on the screen?

**Comment by igormisha** [comment] 2016-01-07 11:55
It outputs black screen.

**Comment by PaulWoitaschek** [comment] 2016-01-23 22:53
Thanks for the pull request @igormisha 

So I made a sample app based on that which just prints the log and a smiley at the end:
[**App here**](https://www.dropbox.com/s/j0g65flepx8tb07/app-debug.apk?dl=0)

What does it print for you (everyone else reading here). Smiley up or down? Do you face the bug?

**Comment by dreamdt** [comment] 2016-01-24 09:21
http://i.imgur.com/mQqmaVb.jpg

**Comment by gladk** [comment] 2016-01-31 18:08
Please, look at the attached screenshot from my phone.
![screenshot_2016-01-31-19-01-41](https://cloud.githubusercontent.com/assets/1476497/12703871/f6480e10-c84d-11e5-8669-9d82ff0332f1.png)

**Comment by tobika** [comment] 2016-01-31 18:37
bug still here and smiley down :(
fairphone, android 4.2.2, thanks for your efforts

**Comment by igormisha** [comment] 2016-01-31 20:25
@gladk , thank you for your report, you say "Please, look at the attached screenshot from my phone. It was affected by the bug." . I'd like to know exactly what you mean. Are there some mono mp3 files on your device which are played with double speed on MaterialAudiobookPlayer?
I'm asking because in the screenshot your codec returned channel count=1 which equals to extractor channel count for mono file, so it should play with normal speed without distortion.

**Comment by gladk** [comment] 2016-01-31 20:32
@igormisha , a couple of months ago I reported the bug https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/317 and it was merged with this bug. I have to use the version 2.2.2, because speed adjustment is critical for me. I had never problem with the normal speed though. 

Sorry, if my screenshot is irrelevant in this case.

**Comment by igormisha** [comment] 2016-02-01 09:40
@gladk  Oh, I see. We are in the same boat. I use patched version of MaterialAudiobookPlayer myself because of the strategy not to provide speed adjustment feature to devices which have problem with channel count.
Anyway, now your report is helpfull as it verifies the correct work of the destinguishing algorithm on your device your device.

**Comment by PaulWoitaschek** [comment] 2016-02-17 16:31
Included as of 2.6.0. Thank you to all contributors, especially @igormisha

**Comment by Marc2112** [comment] 2016-05-08 15:07
Do I understand this correctly? The bug won't be fixed? I've got a phone with disabled playback speed setting.

**Comment by PaulWoitaschek** [comment] 2017-02-21 08:17
Todo: Re-apply fix.

**Comment by lechbaczynski** [comment] 2017-02-26 11:28
Have the same problem. Updated app yesterday, and now it plays too fast, even if I slow it down to 0,5 sped, then the speed is okay, but the voice pitch is too high

**Closed** 2017-03-27 22:57 UTC
Labels: Bug
