### ISSUE TITLE
Audio plays very quickly at high frequencies (like a cartoon voice)

### ISSUE THREAD

**Issue by dbdeveloper** [PaulWoitaschek/MaterialAudiobookPlayer#553] opened 2017-03-04 14:24 UTC
Hi!

Here you can get the original audio file and a screencast where this file has been played. Hope it help you to fix the bug. This bug appeared when speed changing ability was added to the player.

Phone: Fly IQ451, Android version 4.2.1, Linux 3.4.5

[example.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/818664/example.zip)

Have a nice day

**Comment by lechbaczynski** [comment] 2017-03-06 08:02
Got the same problem, perhaps this is duplicate of  #129

**Comment by lechbaczynski** [comment] 2017-03-08 11:12
I have android **4.2.1** too.  **kernel 3.4.5** too. Have the problem with mp3s - for example one of them is 112kbps, other 64kbps.  @PaulWoitaschek , maybe this is the clue?

**Comment by PaulWoitaschek** [comment] 2017-03-10 19:06
Can you check if this is fixed with the [latest release candidate](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v3.0.13-RC)?

**Closed** 2017-03-14 21:49 UTC

**Comment by lechbaczynski** [comment] 2017-03-16 12:05
Sorry, couldn't do that, but downloaded new version today from google play store and it is fixed. Thanks :)
